[theme]
base = "light"
primaryColor = "#437C90"
backgroundColor = "#EEEBD3"
secondaryBackgroundColor = "#F8F7F0"
textColor = "#203F3D"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
