[theme]
base = "dark"
primaryColor = "#FE621D"
backgroundColor = "#100A08"
secondaryBackgroundColor = "#1B110E"
textColor = "#F7EFEB"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
